### ISSUE TITLE
Realm instances properly closed?

### ISSUE THREAD

**Issue by maberer** [patloew/countries#1]
Awesome project - thanks a lot for the demo;

One minor issue though:

I found that realm instances created here:
https://github.com/patloew/countries/blob/ffa6b78199bc51324b364267036465d3fbfc68f9/app/src/main/java/com/patloew/countries/data/local/CountryRepoImpl.java#L45

...are never closed. Either I miss an important point here or a memory leak is created
when the backup store is queried... (`Realm.getInstance()` Is called on every query...)

I am not sure if this is intended... what do I miss?
In activities, the Realm is properly closed within `onDestroy()`... so no problem there.

**Comment by patloew** [comment]
I'm using [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html), which closes the Realm instance at the end of the statement. While this is normally only supported by Android 4.4 or later, Retrolambda backports this to older versions.

**Comment by maberer** [comment]
@patloew Ok thanks that seems reasonable.

Anyway because there is a `detached` boolean on the local data model,
I assume that it is intended to return the `RealmResults` in order to attach
a listener in an activity to get notified on data changes... right?
(this seems to be unused in the example though)

https://github.com/patloew/countries/blob/master/app/src/main/java/com/patloew/countries/data/local/CountryRepoImpl.java#L51

Although not tested, I guess that could be a potential problem because
when attaching a listener on a `RealmResults` object, a check for a valid Realm instance
is performed. 

https://github.com/realm/realm-java/blob/a248ae172bb768a106b592a9cab64ca405e53afe/realm/realm-library/src/main/java/io/realm/RealmResults.java#L926

Because the Realm would be closed on returning by the try-with-ressource, 
I think the following line would throw an exception:

https://github.com/realm/realm-java/blob/ca4bc7c30b66dfbd77c6af32da1b9c5d113a7f77/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L450

I have a hard time to understand the correct use of Realm instances
while applying MVVM pattern (and others) - I do not want to pollute activities
with code that should be in models... (on the other hand,
not being able to use advanced features like Realm notifications is bad as well...)

Do you think RealmResult listeners would work when attached in your activities
the way this is done? Any pointers on architectural patterns/examples?

-Thanks

**Comment by patloew** [comment]
That's the reason why I have a Realm instance open in every Activity (in the BaseActivity). Realm instances are cached for each thread, therefore the Realm is not really closed in my Repo, since the Realm instance in the Activity is still open (given you call the repo methods on the main thread). Just remember that a Realm is only really closed, if it's the last `close()` of an instance on a thread.

As for listeners on RealmResults, these should work as long as your Activity (extending BaseActivity) is running.

**Comment by maberer** [comment]
Cool thanks! That makes a lot of sense now - I overlooked 
the Realm inject in the BaseActivity - thanks again for
your example!

**Comment by patloew** [comment]
I just updated the project to use a `RealmChangeListener`, as an example how this can be used.

**Comment by maberer** [comment]
@patloew Wow thats great. Thanks a lot for your work, really appreciate it!
