### ISSUE TITLE
Why startActivity and replaceFragment remove bundle args 

### ISSUE THREAD

**Issue by muziling** [patloew/countries#10]
ActivityNavigator.kt remove bundle arg function,  what can i use instead of

**Comment by LukaszLyskawa** [comment]
The navigator offers you functions in both languages, that allow you to modify the intent (adding extra arguments or flags etc.).

You can add your bundle using:

Kotlin
```Kotlin
navigator.startActivity(ActivityB::class.java) { putExtra(KEY, YOUR_BUNDLE) }
```

Java
```Java
navigator.startActivity(ActivityB.class, intent -> putExtra(KEY, YOUR_BUNDLE));
```
or
```Java
navigator.startActivity(ActivityB.class, YOUR_BUNDLE)); //Navigator.EXTRA_ARGS key by default
```
