### ISSUE TITLE
Is it possible to inherit ViewHolderComponent from FragmentComponent?

### ISSUE THREAD

**Issue by zsavely** [patloew/countries#3]
It is probably possible but I just can't find a way to to pass a `Fragment` instance to the `FragmentModule` when initializing `BaseViewHolder` and `ViewHolderComponent`.

Or is there a way of interacting with `Fragment` from a `ViewHolder`?

**Comment by patloew** [comment]
Yes it is possible. You have to get the Activity and then use the fragment manager to get the fragment. This finally gives you access to the FragmentComponent. However, you need to make separate classes `BaseFragmentViewHolder` and `FragmentViewHolderComponent` to make this work.
I'll implement this in the project when I find time.

**Comment by j7arsen** [comment]
When you implement this?

**Comment by patloew** [comment]
This is now merged.
