### ISSUE TITLE
Cannot resolve symbol 'DaggerAppComponent'

### ISSUE THREAD

**Issue by reixa00** [patloew/countries#7]
Just checked out the project and imported it to Android Studio.

It says 'Cannot find symbol "DaggerAppComponent"' which should be located inside ../injection/components but it´s not. Has it been replaced or removed? In that case, the CountriesApp.java onCreate() code should be modified?

Thanks!

**Comment by patloew** [comment]
This is a generated class. Did you try building the project?

**Comment by reixa00** [comment]
Yes, you're right. Don't know why it didn't build the project at first, now I forced it to rebuild the project and everything goes smooth.

Thank you and sorry for the inconveniences.
